### ISSUE TITLE
RGB Images of Leader and Follower Views During Gameplay

### ISSUE THREAD

**Issue by Yang011013** [lil-lab/cb2#8]
Hello, I would like to save RGB images of the views of the leader and follower during each game session. Whenever the leader or follower takes an action resulting in an update to their views, I want to save their views as .png or other format RGB images. Where should I add the code for this functionality? I'm not very familiar with frontend and backend knowledge, so I would greatly appreciate your help in solving this problem.

**Comment by jsharf** [comment]
Hello,

While we don't support exact RGB screenshots of the front-end, you can generate images describing the game state (made for this purpose) using the GameDisplay class in src/cb2game/server/map_tools/visualize.py

In fact, there's already a lot of support for generating this from games recorded to the sqlite database. Here's some options:

- 1. Take a script like src/cb2game/server/db_tools/instruction_vis.py and modify it slightly to suit your needs (I recommend running it first, to see if maybe the output is good enough). The command-line parameters, as always in CB2, are specified in the main function:
```
def main(
    max_instructions=-1,
    config_filepath="config/server-config.json",
    output_dir="output",
    research_only=True,
):
```

You probably want to set --config_filepath="...." (point to config file you generated) and also --research_only=False (research_only removes games that fail a base heuristic, like games that ended immediately, have a score of zero, or several other things).

The output will be a bunch of RGB images in output_dir ("output" by default, which is created at current directory when run)

- 2. The pyclient uses visualize behind the scenes to render game state. You can just call endpoint.visualization() to get access to the GameDisplay object (again, see src/cb2game/map_tools/visualize.py). There's a function in visualize.py that shows you how to extract underlying RGB pixels and save to a file. This is useful if you want a bot to save RGB images while it's playing.

- 3. If you *really* want screenshots of the in-game UI, you can use the replay feature and just automate taking screenshots of it. Just go to hostname:port/view/dashboard on your CB2 service, click on a link on the right to view a game, and then at the very top of the page, there's a "view replay" link.

**Comment by jsharf** [comment]
Actually, the best way to do this is likely to use src/cb2game/pyclient/local_game_coordinator.py. You specifically want to use `CreateGameFromDatabase`. Pass in the Event UUID from your database (see Event table... you can browse manually with sqlite browser). It will use the global parameter --config_filepath="..." to locate your database. Then create an endpoint pair, and call leader() and follower() on it to get the underlying endpoints. Call visualization() on each of these to get the GameDisplay object, and then draw to screen using something like:

```
    display = endpoint_pair.leader().visualization()
    pygame.image.save(display.screen(), file_path)
    display = endpoint_pair.follower().visualization()
    pygame.image.save(display.screen(), file_path)
```

For an example of how to use the local game coordinator, check out `local_self_play.py` in src/cb2game/pyclient/demos 

If you're curious what the GameDisplay output looks like, it's something like this (there's lots of optional things you can control, like adding a blue line trajectory to the map, showing the players locations, green/red dots for pos/neg feedback, etc). If you want to show this from the renderer's POV and filter out tiles that they can't see, you can look into src/cb2game/pyclient/follower_data_masking.py. Though using the follower's endpoint as done in the code example above should do this automatically, I don't 100% recall all the details.

<img width="390" alt="Screenshot 2024-03-25 at 12 02 23 PM" src="https://github.com/lil-lab/cb2/assets/86507/7e8ddefe-6e76-4442-b308-d698987e0982">

**Comment by Yang011013** [comment]
Actually, what I'm looking for is to save the real-time screens of both the leader and the follower when the game is playing rather than when replaying the game, or in other words, to save the screen whenever the leader and follower take action resulting in a change in their perspectives. This saving process would be akin to manually taking screenshots of the screen.
leader's view
<img width="895" alt="Snipaste_2024-03-26_11-23-51" src="https://github.com/lil-lab/cb2/assets/76615593/2694ff53-aa4f-43e6-9287-e07e01d83e88">
follower's view
<img width="887" alt="Snipaste_2024-03-26_11-24-01" src="https://github.com/lil-lab/cb2/assets/76615593/4db513e5-8906-438a-b2e5-ca59a6bafd44">

**Comment by jsharf** [comment]
Do you actually need it to be live, during the game? Or can it be done after the fact and recreated from the recording? I can't really see why you would need it to be live.

And if so, wouldn't the pyclient API that lets you connect from a python script work?

Maybe you can make some tooling that takes screenshots automatically? Modifying the frontend requires unity development, which is in C# and is a bit more involved, so I would recommend working around it.

Maybe if you tell me a bit more about why you need it to be live in-game, I can help you more.

**Comment by Yang011013** [comment]
Inspired by your use of GPT-3.5 as a follower, I appreciate the script you provided, which uses formatted language descriptions of the follower's first-person perspective as prompts. However, I'm interested in exploring the multimodal capabilities of some large models. My idea involves incorporating the RGB image of the follower's first-person perspective as part of the prompt. This way, the large model can act more like a human follower, responding to both the first-person view and the leader's instructions to take actions.

**Comment by jsharf** [comment]
We made the GameDisplay specifically for image multimodal inputs. If you access the GameDisplay object through the follower's GameEndpoint, then it already masks out everything they can't see (though, I suppose you can see behind objects... we didn't mask out occlusions). The view is still top-down, however only objects that are visible from first person view are visible.

It's possible to modify the front-end to spit out screenshots, but it's a bit of work, and theoretically with fine-tuning you should be able to get decent performance using these images.

If I had more time, I think it would be more useful to create an open source 3D solution, so we don't have to use Unity tooling for this, as it's very annoying to develop for. This could involve Godot or something on top of pygame like pyengine3d.

**Comment by Yang011013** [comment]
I suppose I have tested this feature before. Is the follower's view as shown in the image below?
![follower_visibility](https://github.com/lil-lab/cb2/assets/76615593/4be1a40e-e3a2-4f88-937d-0798a34f2881)

**Comment by jsharf** [comment]
Yes, that's it. We don't have a supported way of doing POV from in-game.

I suppose if you want to generate a follower's POV, you're probably better off recreating a 3D view from the map data. The assets are in FBX format, which [can be converted to a more open format](https://github.com/godotengine/FBX2glTF). It's a bit of work, but I can try to assist by pointing at relevant code in the front end. If you end up making this, it would be appreciated if you submit this to CB2.

Handles all game-related network messages:
https://github.com/lil-lab/cb2/blob/main/unity_client/Assets/Scripts/Network/NetworkRouter.cs

Hex grid (probably most important file):
https://github.com/lil-lab/cb2/blob/main/unity_client/Assets/Scripts/HexGridManager.cs

Thin wrapper around hex grid:
https://github.com/lil-lab/cb2/blob/main/unity_client/Assets/Scripts/HexGrid.cs

Represents a single cell in the grid (both its coordinate & the boundary):
https://github.com/lil-lab/cb2/blob/main/unity_client/Assets/Scripts/HexCell.cs

Represents boundaries around a cell (for checking collisions, so you can't walk into objects):
https://github.com/lil-lab/cb2/blob/main/unity_client/Assets/Scripts/HexBoundary.cs

Represents [Hexagonal Coordinates](https://en.wikipedia.org/wiki/Hexagonal_Efficient_Coordinate_System) of cells using HECS:
https://github.com/lil-lab/cb2/blob/main/unity_client/Assets/Scripts/HecsCoord.cs

Owns all entities (props & actors. a "prop" is really just a card, but I was thinking to have other interactive objects too. Actors are players like leader & follower), lets you queue up animations or actions on them:
https://github.com/lil-lab/cb2/blob/main/unity_client/Assets/Scripts/EntityManager.cs

Prop class (used by EntityManager to manage props. Also just a generic wrapper around Unity GameObject, reused by Actor):
https://github.com/lil-lab/cb2/blob/main/unity_client/Assets/Scripts/Prop.cs

Player class (leader & follower, used by Entity manager):
https://github.com/lil-lab/cb2/blob/main/unity_client/Assets/Scripts/Player.cs

Actor class (thin wrapper around Prop class for easier use by Player class. This should have just been merged with the Player class and doesn't need to be its own distinct class, I think):
https://github.com/lil-lab/cb2/blob/main/unity_client/Assets/Scripts/Actor.cs

Generates cards from JSON description (see FromNetwork()):
https://github.com/lil-lab/cb2/blob/main/unity_client/Assets/Scripts/CardBuilder.cs

Discrete & continuous representation of actor/prop state (distinction is probably not necessary, but the code linearly interpolates between discrete states to get continuous points when the actors move between cells):
https://github.com/lil-lab/cb2/blob/main/unity_client/Assets/Scripts/State.cs

This directory contains implementations of different animation types (specializations of Action.cs). Note that animations also displace elements:
https://github.com/lil-lab/cb2/tree/main/unity_client/Assets/Scripts/Actions

Queue of actions -- you can queue up actions and then as Update() is called, they are automatically applied to state, you can call ContinuousState() to get the interpolated live location, or State() to get the latest completed discrete location:
https://github.com/lil-lab/cb2/blob/main/unity_client/Assets/Scripts/ActionQueue.cs

Owns the network router and handles game-management related things, like joining the wait queue or joining a new room, or quitting a game. Also fetches server config:
https://github.com/lil-lab/cb2/blob/main/unity_client/Assets/Scripts/Network/NetworkManager.cs

Loads map from the network and prepares a list of tiles for HexGridManager to use to generate a map:
https://github.com/lil-lab/cb2/blob/main/unity_client/Assets/Scripts/Network/NetworkMapSource.cs

Generic asset loading interface:
https://github.com/lil-lab/cb2/blob/main/unity_client/Assets/Scripts/IAssetSource.cs

Unity asset loading implementation, contains paths to all the assets:
https://github.com/lil-lab/cb2/blob/main/unity_client/Assets/Scripts/UnityAssetSource.cs

I don't think you'll need to know all of these, but hopefully this is enough of a map to begin doing this.
