### ISSUE TITLE
A feedback module

### ISSUE THREAD

**Issue by Yang011013** [lil-lab/cb2#9]
Hello, could we add a feedback module to the cb2 game? Primarily, it would involve feedback from the follower to the leader. For example, when the leader sends instruction that are ambiguous or difficult for the follower to understand, the follower can send feedback to the leader in natural language form, informing the leader that his instruction is difficult to understand. If possible, would implementing this module be very difficult?

**Comment by yoavartzi** [comment]
This is a great idea, and something we have been wanting to do. Unfortunately, we don't have the engineering capacity to do this in the foreseeable future. But we encourage you to give it a try. There's some engineering overhead, but a few days of work and learning should do the trick.

**Comment by yoavartzi** [comment]
The front-end UI would require changes to let the follower respond back to the leader.
